export const APIKey = '246cdb7491bc3f549cd0189615c86254';
export const imgURL = 'https://image.tmdb.org/t/p/w500';
export const MOVIE_API = 'https://api.themoviedb.org/3/'
export const SEARCH_API_MOVIE = MOVIE_API + 'search/movie'
export const DISCOVER_API_MOVIE = MOVIE_API + 'discover/movie'
export const BACKDROP_PATH = 'https://image.tmdb.org/t/p/w1280'
export const TOP_MOVIE = MOVIE_API + 'movie/top_rated'
export const SEARCH_API_SERIE = MOVIE_API + 'search/tv'
export const DISCOVER_API_SERIE = MOVIE_API + 'discover/tv'